PACKAGE_NAME="lian-li-sl-infinity"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="Lian_Li_SL_INFINITY"
DEST_MODULE_LOCATION[0]="/extra"
MAKE[0]="make KERNEL_VERSION=${kernelver} all"
CLEAN="make KERNEL_VERSION=${kernelver} clean"
AUTOINSTALL="yes"
